include!("memory_parts/part01.rs");
include!("memory_parts/part02.rs");
include!("memory_parts/part03.rs");
include!("memory_parts/part04.rs");
include!("memory_parts/part05.rs");
include!("memory_parts/part06.rs");
include!("memory_parts/part07.rs");
include!("memory_parts/part08.rs");
include!("memory_parts/part09.rs");
